SAMPLE_FREQ = 0
FILE_LOCATION = r"C:\Data"
FILE_NAME = None
MULTI_FILE_NAME = []
FILE_NAME_INIT = "No File Chosen"
FILE_SUFFIX = None
FILE_NAME_SAVE = "_out"
FILE_NAME_MULTI_FILE_SAVE = "multi_file_out"
FILE_SAVE_SINGLE_COLUMN = 0
FILE_SAVE_FRAMES = 1

ROW_HEADER = 0
DATA_ROW_START_INDEX_DEFAULT = 1
DATA_LENGTH_REQUESTED_DEFAULT = 0
PROCESS_ALL_COLUMNS = 0
N_ROWS_TO_PEAK = 5
PROCESS_ONLY = 0
PROCESS_AND_PLOT = 1
TIMESTAMP_EXTRACT = 0
TIMESTAMP_INCLUDE = 0
DELIMITER_TYPE_COMMA = 0
DELIMITER_TYPE_TAB = 1

MULTI_FILES = False
# MULTI_FILES = True

COLUMNS_ALL = 0
COLUMNS_SELECT = 1
HEADER_INCLUDE_PLOTS = 1
HEADER_INCLUDE_PLOTS_NOT = 0
HEADER_INCLUDE_FILES = 1
HEADER_INCLUDE_FILES_NOT = 0
PLOTS_OVERLAP = 0
INCLUDE_PLOT_TITLE = False
PLOT_TITLE = ''

OPTION_PEAK_FILE = 0
OPTION_PROCESS_FILE = 1
