
SAMPLE_FREQ = 0
FILE_LOCATION = r"C:\Mic_Data"
FILE_NAME = None
FILE_NAME_INIT = "No File Chosen"
FILE_SUFFIX = None
FILE_NAME_SAVE = "_out"
FILE_SAVE_SINGLE_COLUMN = 0
FILE_SAVE_FRAMES = 1

ROW_HEADER = 0
ROW_DATA_START = 1
ROW_DATA_END = 0
PROCESS_ALL_COLUMNS = 0
N_ROWS_TO_PEAK = 5
PROCESS_ONLY = 0
PROCESS_AND_PLOT = 1
TIMESTAMP_EXTRACT = 0
TIMESTAMP_INCLUDE = 0
DELIMITER_TYPE_COMMA = 0
DELIMITER_TYPE_TAB = 1

COLUMNS_ALL = 0
COLUMNS_SELECT = 1
HEADER_INCLUDE = 1
HEADER_INCLUDE_NOT = 0

OPTION_PEAK_FILE = 0
OPTION_PROCESS_FILE = 1
